const char *default_config =
//"omx_dummy,   parent-type=GstOmxDummy, type=GstOmxDummyOne, library-name=libomx_sharedlibrary.so, component-name=OMX.bellagio.dummy,      rank=0;"
//"omx_dummy_2, parent-type=GstOmxDummy, type=GstOmxDummyTwo, library-name=libomx_sharedlibrary.so, component-name=OMX.PV.dummy2,           rank=256;"
"omx_mpeg4dec,                         type=GstOmxMpeg4Dec, library-name=libomx_sharedlibrary.so, component-name=OMX.PV.mpeg4dec,         rank=256;"
"omx_h264dec,                          type=GstOmxH264Dec,  library-name=libomx_sharedlibrary.so, component-name=OMX.PV.avcdec,           rank=256;"
"omx_h263dec,                          type=GstOmxH263Dec,  library-name=libomx_sharedlibrary.so, component-name=OMX.PV.h263dec,          rank=256;"
"omx_wmvdec,                           type=GstOmxWmvDec,   library-name=libomx_sharedlibrary.so, component-name=OMX.PV.wmvdec,           rank=256;"
"omx_mpeg4enc,                         type=GstOmxMpeg4Enc, library-name=libomx_sharedlibrary.so, component-name=OMX.PV.mpeg4enc,         rank=256;"
"omx_h264enc,                          type=GstOmxH264Enc,  library-name=libomx_sharedlibrary.so, component-name=OMX.PV.avcenc,           rank=256;"
"omx_h263enc,                          type=GstOmxH263Enc,  library-name=libomx_sharedlibrary.so, component-name=OMX.PV.h263enc,          rank=256;"
"omx_vorbisdec,                        type=GstOmxVorbisDec,library-name=libomx_sharedlibrary.so, component-name=OMX.PV.audio_decoder.ogg.single, rank=128;"
"omx_mp3dec,                           type=GstOmxMp3Dec,   library-name=libomx_sharedlibrary.so, component-name=OMX.PV.mp3dec,           rank=256;"
"omx_audiosink,                        type=GstOmxAudioSink,library-name=libomx_sharedlibrary.so, component-name=OMX.PV.alsa.alsasink,    rank=0;"
"omx_volume,                           type=GstOmxVolume,   library-name=libomx_sharedlibrary.so, component-name=OMX.PV.volume.component, rank=0;"
;
